name: 01 - Building Blocks
on: push
# on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "i will pass"
          exit 0
      - name: Multi-line bash
        run: |
          echo "Hello, world!"
          echo "I am a multi-line bash script"
          echo "I will also pass"
      - name: Say goodbye
        run: echo "Goodbye, world!"
