name: 15 - Working with Matrices

on: workflow_dispatch

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }} - ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ububtu-latest]
    runs-on: ${{ matrix.node-version }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
