name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
          target-directory: dummy_dir
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: ravraw/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
