name: 19 - 1 - Managing Concurrency

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - "https://www.google.com"
          - "https://www.invalid-aidfghaidgfiazgd.com"
          - "invalid-aidfghaidgfiazgd"
      max_trials:
        description: Maximum trials until action fails.
        default: "20"
        required: false
      delay:
        description: Delay in seconds between trials.
        default: "5"
        required: false

concurrency:
  group: ${{github.workflow}}-${{github.ref}}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
